return {
  'barreiroleo/ltex_extra.nvim',
  ft = {
    'bib',
    'gitcommit',
    'mail',
    'markdown',
    'mdx',
    'org',
    'norg',
    'plaintex',
    'rst',
    'rnoweb',
    'latex',
    'tex',
    'text',
    'pandoc',
  },
  dependencies = 'neovim/nvim-lspconfig',
  opts = {
    -- ltex_extra options
    {
      load_langs = { 'en-US', 'fr-FR' },
      init_check = true,
    },
    -- ltex-ls options
    server_opts = {
      settings = {
        ltex = {
          enabled = {
            'bib',
            'gitcommit',
            'mail',
            'markdown',
            'mdx',
            'org',
            'norg',
            'plaintex',
            'rst',
            'rnoweb',
            'latex',
            'tex',
            'text',
            'pandoc',
          },
          language = 'en-US',
          diagnosticSeverity = 'hint',
          sentenceCacheSize = 2000,
          additionalRules = {
            enablePickyRules = true,
          },
          dictionary = {
            ['en-US'] = {
              'FaaS',
              'QoS',
              "Grid'5000",
              'testbed',
              'testbeds',
              'Testbeds',
              'testbed',
              'Max-cpu',
              'EdgeDecAp',
              'FNs',
              'AirBnB',
              'Voronoi',
              'FOGPLAN',
              'Hermod',
              'Emufog',
              'autoscaler',
              'Autoscaler',
              'Paradoxally',
              'GIRAFF',
              'eBPF',
              'OpenFaaS',
              'Netem',
              'MinCPU',
              'QoS',
              'Inria',
              'INSA',
              'Irisa',
            },
          },
          disabledRules = {
            ['en-US'] = { 'WHITESPACE_RULE', 'MORFOLOGIK_RULE_EN_US' },
          },
        },
      },
    },
  },
}
